#
# runtime configuration section
#
machines:
  # SHORT VERSION
  # each machine must have a unique 'id' value
  # each machine must consist of the following references:
  #  base: driver configuration
  #    *machine-base
  #  disabled override: (optional) set machine inactive
  #    *machine-disabled
  #  source: where to get data
  #    -- user defined reference
  #  collector: what data to collect
  #    -- user defined reference
  #  target: where to send data
  #    -- user defined reference
  #  filter: how to filter data
  #    *change-filter - send only when data changes
  #    *no-filter - send all data, regardless of change

  #- id: example-null
  #  <<: *machine-base
  #  <<: *machine-disabled
  #  <<: *source-1
  #  <<: *collector-1
  #  <<: *target-null
  #  <<: *change-filter

  #- id: example-mqtt
  #  <<: *machine-base        # base Fanuc configuration
  #  <<: *machine-disabled    # omit this machine setup from runtime; remove to make active
  #  <<: *source-1            # where to get data
  #  <<: *collector-1         # what data to get and how to transform data
  #  <<: *target-mqtt-1       # where to send data
  #  <<: *change-filter       # data filter

  #- id: example-influx
  #  <<: *machine-base
  #  <<: *machine-disabled
  #  <<: *source-1
  #  <<: *collector-1
  #  <<: *target-influx-1
  #  <<: *change-filter

  #- id: example-spb
  #  <<: *machine-base
  #  <<: *machine-disabled
  #  <<: *source-1
  #  <<: *collector-1
  #  <<: *target-spb-1
  #  <<: *change-filter

  #- id: f_sim_mtc_short
  #  <<: *machine-base
  #  <<: *machine-disabled
  #  <<: *source-1
  #  <<: *collector-1
  #  <<: *target-shdr-1
  #  <<: *no-filter
  
  # LONG VERSION
  - id: f_sim_mqtt_long
    enabled: !!bool false
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy: l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc
    handler: l99.driver.fanuc.handlers.FanucOne, fanuc
    transport: l99.driver.fanuc.transports.MQTT, fanuc
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: !!int 1000
      net:
        ip: 10.1.10.211
        port: !!int 8193
        timeout_s: !!int 3
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      stay_connected: !!bool false
      #exclusions:
      #  1: 
      #  2: [ X, S ]
      #  3: [ % ]
      collectors:
      - l99.driver.fanuc.collectors.MachineInfo, fanuc
      - l99.driver.fanuc.collectors.Alarms, fanuc
      - l99.driver.fanuc.collectors.Messages, fanuc
      - l99.driver.fanuc.collectors.StateData, fanuc
      - l99.driver.fanuc.collectors.ToolData, fanuc
      - l99.driver.fanuc.collectors.ProductionData, fanuc
      #- l99.driver.fanuc.collectors.ProductionDataExternalSubprogramDetails, fanuc
      - l99.driver.fanuc.collectors.GCodeData, fanuc
      - l99.driver.fanuc.collectors.AxisData, fanuc
      - l99.driver.fanuc.collectors.SpindleData, fanuc
    l99.driver.fanuc.handlers.FanucOne, fanuc:
      change_only: !!bool true
      skip_internal: !!bool true
    l99.driver.fanuc.transports.MQTT, fanuc:
      topic: fanuc/{{machine.Id}}/{{veneer.Name}}{{if veneer.SliceKey}}/{{veneer.SliceKey}}{{end}}
      net:
        type: tcp
        ip: 127.0.0.1
        port: !!int 1883
      anonymous: !!bool true
      user: 
      password: 
    l99.driver.fanuc.collectors.Alarms, fanuc:
      stateful: !!bool true
    l99.driver.fanuc.collectors.Messages, fanuc:
      stateful: !!bool true
    l99.driver.fanuc.collectors.ProductionData, fanuc:
      unsupported: !!bool false
    l99.driver.fanuc.collectors.GCodeData, fanuc:
      block_counter: !!bool false
      buffer_length: !!int 512
    l99.driver.fanuc.collectors.ProductionDataExternalSubprogramDetails, fanuc:
      extraction:
        files:
          1: "c:/partprg/one"
          1400: "c:/partprg/MCenter"
          1401: "c:/partprg/PLeft"
          1402: "c:/partprg/PRight"
        lines: 
          count: !!int 60
          show: !!bool false
          keep: !!bool false
        properties:
          keep: !!bool true
          map:
            program_name: "^\\( *(?<key>PROGRAM NAME) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"
            feed: "^\\( *(?<key>FEED) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"
            time_per_program: "^\\( *(?<key>TIME/PROGRAM) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"
            kits_per_program: "^\\( *(?<key>KITS/PROGRAM) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"
            comments: "^\\( *(?<key>COMMENTS) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"

  - id: f_sim_mtc_long
    enabled: !!bool true
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy: l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc
    handler: l99.driver.fanuc.handlers.FanucOne, fanuc
    transport: l99.driver.fanuc.transports.SHDR, fanuc
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: !!int 1000
      net:
        ip: 10.1.10.211
        port: !!int 8193
        timeout_s: !!int 3
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      stay_connected: !!bool false
      #exclusions:
      #  1: 
      #  2: [ X, S ]
      #  3: [ % ]
      collectors:
      - l99.driver.fanuc.collectors.MachineInfo, fanuc
      - l99.driver.fanuc.collectors.Alarms, fanuc
      - l99.driver.fanuc.collectors.Messages, fanuc
      - l99.driver.fanuc.collectors.StateData, fanuc
      - l99.driver.fanuc.collectors.ToolData, fanuc
      - l99.driver.fanuc.collectors.ProductionData, fanuc
      - l99.driver.fanuc.collectors.GCodeData, fanuc
      - l99.driver.fanuc.collectors.AxisData, fanuc
      - l99.driver.fanuc.collectors.SpindleData, fanuc
    l99.driver.fanuc.handlers.FanucOne, fanuc:
      change_only: !!bool false
      skip_internal: !!bool true
    l99.driver.fanuc.transports.SHDR, fanuc:
      << : *default-shdr-transformers
      << : *default-shdr-model-genny
      device_key: ~
      device_name: f_sim
      net:
        port: !!int 7878
        heartbeat_ms: !!int 10000
        interval_ms: !!int 1000
    l99.driver.fanuc.collectors.Alarms, fanuc:
      stateful: !!bool true
    l99.driver.fanuc.collectors.Messages, fanuc:
      stateful: !!bool true

  - id: f_sim_spb_long
    enabled: !!bool false
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy: l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc
    handler: l99.driver.fanuc.handlers.FanucOne, fanuc
    transport: l99.driver.fanuc.transports.SpB, fanuc
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: !!int 1000
      net:
        ip: 10.1.10.211
        port: !!int 8193
        timeout_s: !!int 3
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      stay_connected: !!bool false
      collectors:
      - l99.driver.fanuc.collectors.MachineInfo, fanuc
      - l99.driver.fanuc.collectors.Alarms, fanuc
      - l99.driver.fanuc.collectors.Messages, fanuc
      - l99.driver.fanuc.collectors.StateData, fanuc
      - l99.driver.fanuc.collectors.ToolData, fanuc
      - l99.driver.fanuc.collectors.ProductionData, fanuc
      #- l99.driver.fanuc.collectors.ProductionDataExternalSubprogramDetails, fanuc
      - l99.driver.fanuc.collectors.GCodeData, fanuc
      - l99.driver.fanuc.collectors.AxisData, fanuc
      - l99.driver.fanuc.collectors.SpindleData, fanuc
    l99.driver.fanuc.transports.SpB, fanuc:
      overrides:
        scada_id: ~
        group_id: ~
        node_id: ~
        device_id: ~
      net:
        type: tcp
        ip: 10.1.10.2
        port: !!int 1883
      anonymous: !!bool false
      user: admin
      password: password
      reconnect_s: !!int 30

  - id: f_sim_influx_long
    enabled: !!bool false
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy: l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc
    handler: l99.driver.fanuc.handlers.FanucOne, fanuc
    transport: l99.driver.fanuc.transports.InfluxLP, fanuc
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: !!int 1000
      net:
        ip: 10.1.10.211
        port: !!int 8193
        timeout_s: !!int 3
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      stay_connected: !!bool false
      collectors:
      - l99.driver.fanuc.collectors.MachineInfo, fanuc
      - l99.driver.fanuc.collectors.Alarms, fanuc
      - l99.driver.fanuc.collectors.Messages, fanuc
      - l99.driver.fanuc.collectors.StateData, fanuc
      - l99.driver.fanuc.collectors.ToolData, fanuc
      - l99.driver.fanuc.collectors.ProductionData, fanuc
      - l99.driver.fanuc.collectors.GCodeData, fanuc
      - l99.driver.fanuc.collectors.AxisData, fanuc
      - l99.driver.fanuc.collectors.SpindleData, fanuc
    l99.driver.fanuc.transports.InfluxLP, fanuc:
      <<: *default-influx-transformers
      host: "http://influx:8086"
      token: "dewlnpy0CmcikwWmMBlqoxcoeuUWpdlDQi8yH7QyGU0tcfn0avMMcpPWYJ-ZUmLD8iHXNl27M3GBHGC4n4_EwA=="
      org: "fanuc"
      bucket: "fanuc"
