machines:
  - id: example-sim-dev
    enabled: !!bool true
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy: l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc
    #strategy: l99.driver.fanuc.strategies.GCodeData, fanuc
    handler: l99.driver.fanuc.handlers.FanucOne, fanuc
    #handler: l99.driver.fanuc.handlers.FanucMTC, fanuc
    transport: l99.driver.fanuc.transports.MQTT, fanuc
    #transport: l99.driver.fanuc.transports.SHDR, fanuc
    
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: !!int 1000
      net_ip: 10.1.10.211
      #net_ip: 172.16.13.100
      net_port: !!int 8193
      net_timeout_s: !!int 3
    
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      #- l99.driver.fanuc.collectors.ParameterDump, fanuc
      #- l99.driver.fanuc.collectors.DiagnosisDump, fanuc
      #- l99.driver.fanuc.collectors.PmcDump, fanuc
      - l99.driver.fanuc.collectors.MachineInfo, fanuc
      - l99.driver.fanuc.collectors.Alarms, fanuc
      - l99.driver.fanuc.collectors.Messages, fanuc
      - l99.driver.fanuc.collectors.StateData, fanuc
      - l99.driver.fanuc.collectors.ProductionData, fanuc
      #- l99.driver.fanuc.collectors.GCodeData, fanuc
      - l99.driver.fanuc.collectors.AxisData, fanuc
      - l99.driver.fanuc.collectors.SpindleData, fanuc
    
    l99.driver.fanuc.transports.MQTT, fanuc:
      enabled: !!bool true
      net_ip: 10.1.10.210
      net_port: !!int 1883
      anonymous: !!bool true
      user:
      password:
    
    l99.driver.fanuc.transports.SHDR, fanuc:
      enabled: !!bool true
      net_port: !!int 7878
      dataitems:
        - observation: "${machine}.connect+avail"
          category: EVENT
          script: |
            return NV == true and 'AVAILABLE' or 'UNAVAILABLE'
        - observation: "${machine}.${path}.machine+hwver"
          foreach: !!bool true
          category: EVENT
          script: |
            return NV.mt_type .. ' ' .. 
                    NV.cnc_type .. ' ' ..
                    NV.series .. ' ' ..
                    NV.model .. ' ' ..
                    NV.version
        - observation: "${machine}.${path}.${axis}.axis+abs"
          foreach: !!bool true
          category: SAMPLE
          script: |
            return NV.position.absolute
        #- observation: "${machine}.${path}.${axis}.axis+dis"
        #  foreach: !!bool true
        #  category: SAMPLE
        #  script: |
        #    return NV.position.distance
        #- observation: "${machine}.${path}.${axis}.axis+mach"
        #  foreach: !!bool true
        #  category: SAMPLE
        #  script: |
        #    return NV.position.machine
        - observation: "${machine}.${path}.${axis}.axis+rel"
          foreach: !!bool true
          category: SAMPLE
          script: |
            return NV.position.relative
        - observation: "${machine}.${path}.${axis}.axis+rel"
          foreach: !!bool true
          category: SAMPLE
          script: |
        - observation: "${machine}.${path}.${axis}.axis+travel"
          foreach: !!bool true
          category: CONDITION
          script: |
            return NV.overtravel == true and 'FAULT' or 'NORMAL'
        - observation: "${machine}.${path}.${axis}.axis+heat"
          foreach: !!bool true
          category: CONDITION
          script: |
            return NV.overheat == true and 'FAULT' or 'NORMAL'
        - observation: "${machine}.${path}.${axis}.axis+servo"
          foreach: !!bool true
          category: CONDITION
          script: |
            return NV.overtravel == true and 'FAULT' or 'NORMAL'
        - observation: "${machine}.${path}.${axis}.axis+frt"
          foreach: !!bool true
          category: SAMPLE
          script: |
            return NV.feed
        - observation: "${machine}.${path}.${axis}.axis+servotemp"
          foreach: !!bool true
          category: SAMPLE
          script: |
            return NV.servo_temp
        - observation: "${machine}.${path}.${axis}.axis+codertemp"
          foreach: !!bool true
          category: SAMPLE
          script: |
            return NV.coder_temp
        - observation: "${machine}.${path}.${axis}.axis+power"
          foreach: !!bool true
          category: SAMPLE
          script: |
            return NV.power
        - observation: "${machine}.${path}.${axis}.axis+state"
          foreach: !!bool true
          category: EVENT
          script: |
            return NV.motion == true and 'TRAVEL' or 'STOPPED'