machines:
  - id: sim
    enabled: !!bool true
    net_ip: 10.20.30.101
    net_port: !!int 8193
    net_timeout_s: !!int 2
    strategy_type: fanuc.collectors.Basic06, fanuc
    sweep_ms: !!int 1000
    handler_type: fanuc.handlers.SplunkMetric, fanuc
    broker:
      enabled: !!bool true
      net_ip: 10.20.30.102
      net_port: !!int 1883
      publish_status: !!bool true
      publish_arrivals: !!bool true
      publish_changes: !!bool true

  - id: naka
    enabled: !!bool false
    net_ip: 172.16.13.100
    net_port: !!int 8193
    net_timeout_s: !!int 5
    strategy_type: fanuc.collectors.Basic06, fanuc
    sweep_ms: !!int 1000
    handler_type: fanuc.handlers.Native, fanuc
    broker:
      enabled: !!bool false
      net_ip: 172.16.10.3
      net_port: !!int 1883
      publish_status: !!bool true
      publish_arrivals: !!bool true
      publish_changes: !!bool true