#
# runtime configuration section
#
machines:
  - id: f_sim_mqtt_long
    enabled: !!bool true
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy: l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc
    handler: l99.driver.fanuc.handlers.FanucOne, fanuc
    transport: l99.driver.fanuc.transports.MQTT, fanuc
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: !!int 1000
      net:
        ip: 10.1.10.211
        port: !!int 8193
        timeout_s: !!int 3
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      stay_connected: !!bool true
      #exclusions:
      #  1: 
      #  2: [ X, S ]
      #  3: [ % ]
      collectors:
      - l99.driver.fanuc.collectors.MachineInfo, fanuc
      - l99.driver.fanuc.collectors.Alarms, fanuc
      - l99.driver.fanuc.collectors.Messages, fanuc
      - l99.driver.fanuc.collectors.StateData, fanuc
      - l99.driver.fanuc.collectors.ToolData, fanuc
      #- l99.driver.fanuc.collectors.ProductionData, fanuc
      - l99.driver.fanuc.collectors.ProductionDataExternalSubprogramDetails, fanuc
      - l99.driver.fanuc.collectors.GCodeData, fanuc
      - l99.driver.fanuc.collectors.AxisData, fanuc
      - l99.driver.fanuc.collectors.SpindleData, fanuc
    l99.driver.fanuc.handlers.FanucOne, fanuc:
      change_only: !!bool true
      skip_internal: !!bool true
    l99.driver.fanuc.transports.MQTT, fanuc:
      topic: fanuc/{{machine.Id}}/{{veneer.Name}}{{if veneer.SliceKey}}/{{veneer.SliceKey}}{{end}}
      enabled: !!bool true
      net:
        type: tcp
        ip: 127.0.0.1
        port: !!int 1883
      anonymous: !!bool true
      user:
      password:
    l99.driver.fanuc.collectors.ProductionData, fanuc:
      unsupported: !!bool true
    l99.driver.fanuc.collectors.GCodeData, fanuc:
      block_counter: !!bool false
      buffer_length: !!int 512
    l99.driver.fanuc.collectors.ProductionDataExternalSubprogramDetails, fanuc:
      extraction:
        files:
          1: "c:/partprg/one"
          1400: "c:/partprg/MCenter"
          1401: "c:/partprg/PLeft"
          1402: "c:/partprg/PRight"
        lines: 
          count: !!int 60
          show: !!bool false
          keep: !!bool false
        properties:
          keep: !!bool true
          map:
            program_name: "^\\( *(?<key>PROGRAM NAME) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"
            feed: "^\\( *(?<key>FEED) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"
            time_per_program: "^\\( *(?<key>TIME/PROGRAM) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"
            kits_per_program: "^\\( *(?<key>KITS/PROGRAM) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"
            comments: "^\\( *(?<key>COMMENTS) *: *(?<value>[^\\):\\n]+[^ \\):\\n])* *\\)$"

  - id: f_sim_mtc_long
    enabled: !!bool false
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy: l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc
    handler: l99.driver.fanuc.handlers.FanucOne, fanuc
    transport: l99.driver.fanuc.transports.SHDR, fanuc
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: !!int 1000
      net:
        ip: 10.1.10.211
        port: !!int 8193
        timeout_s: !!int 3
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      stay_connected: !!bool false
      #exclusions:
      #  1: 
      #  2: [ X, S ]
      #  3: [ % ]
      collectors:
      #- l99.driver.fanuc.collectors.MachineInfo, fanuc
      #- l99.driver.fanuc.collectors.Alarms, fanuc
      #- l99.driver.fanuc.collectors.Messages, fanuc
      #- l99.driver.fanuc.collectors.StateData, fanuc
      #- l99.driver.fanuc.collectors.ToolData, fanuc
      - l99.driver.fanuc.collectors.ProductionData, fanuc
      #- l99.driver.fanuc.collectors.GCodeData, fanuc
      #- l99.driver.fanuc.collectors.AxisData, fanuc
      #- l99.driver.fanuc.collectors.SpindleData, fanuc
    l99.driver.fanuc.handlers.FanucOne, fanuc:
      change_only: !!bool false
      skip_internal: !!bool true
    l99.driver.fanuc.transports.SHDR, fanuc:
      << : *default-shdr-transformers
      << : *default-shdr-model-genny
      device_name: f_sim
      net:
        port: !!int 7878
        heartbeat_ms: !!int 10000
        interval_ms: !!int 1000

  - id: f_sim_spb_long
    enabled: !!bool false
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy: l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc
    handler: l99.driver.fanuc.handlers.FanucOne, fanuc
    transport: l99.driver.fanuc.transports.SpB, fanuc
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: !!int 1000
      net:
        ip: 10.1.10.211
        port: !!int 8193
        timeout_s: !!int 3
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      stay_connected: !!bool false
      #exclusions:
      #  1: 
      #  2: [ X, S ]
      #  3: [ % ]
      collectors:
      - l99.driver.fanuc.collectors.MachineInfo, fanuc
      - l99.driver.fanuc.collectors.Alarms, fanuc
      - l99.driver.fanuc.collectors.Messages, fanuc
      - l99.driver.fanuc.collectors.StateData, fanuc
      - l99.driver.fanuc.collectors.ToolData, fanuc
      - l99.driver.fanuc.collectors.ProductionData, fanuc
      - l99.driver.fanuc.collectors.GCodeData, fanuc
      - l99.driver.fanuc.collectors.AxisData, fanuc
      - l99.driver.fanuc.collectors.SpindleData, fanuc
    l99.driver.fanuc.handlers.FanucOne, fanuc:
      change_only: !!bool true
      skip_internal: !!bool true
    l99.driver.fanuc.transports.SpB, fanuc:
      enabled: !!bool true
      net:
        type: tcp
        ip: 10.1.10.2
        port: !!int 1883
      anonymous: !!bool false
      user: admin
      password: password

  - id: f_sim_influx_long
    enabled: !!bool false
    type: l99.driver.fanuc.FanucMachine, fanuc
    strategy: l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc
    handler: l99.driver.fanuc.handlers.FanucOne, fanuc
    transport: l99.driver.fanuc.transports.InfluxLP, fanuc
    l99.driver.fanuc.FanucMachine, fanuc:
      sweep_ms: !!int 1000
      net:
        ip: 10.1.10.211
        port: !!int 8193
        timeout_s: !!int 3
    l99.driver.fanuc.strategies.FanucMultiStrategy, fanuc:
      stay_connected: !!bool false
      #exclusions:
      #  1: 
      #  2: [ X, S ]
      #  3: [ % ]
      collectors:
      - l99.driver.fanuc.collectors.MachineInfo, fanuc
      - l99.driver.fanuc.collectors.Alarms, fanuc
      - l99.driver.fanuc.collectors.Messages, fanuc
      - l99.driver.fanuc.collectors.StateData, fanuc
      - l99.driver.fanuc.collectors.ToolData, fanuc
      - l99.driver.fanuc.collectors.ProductionData, fanuc
      - l99.driver.fanuc.collectors.GCodeData, fanuc
      - l99.driver.fanuc.collectors.AxisData, fanuc
      - l99.driver.fanuc.collectors.SpindleData, fanuc
    l99.driver.fanuc.handlers.FanucOne, fanuc:
      change_only: !!bool true
      skip_internal: !!bool true
    l99.driver.fanuc.transports.InfluxLP, fanuc:
      l99.driver.fanuc.transports.InfluxLP, fanuc:
      <<: *default-influx-transformers
      host: "http://influx:8086"
      token: "dewlnpy0CmcikwWmMBlqoxcoeuUWpdlDQi8yH7QyGU0tcfn0avMMcpPWYJ-ZUmLD8iHXNl27M3GBHGC4n4_EwA=="
      org: "fanuc"
      bucket: "fanuc"