version: '3.5'

services:
  fanuc_driver:
    container_name: fanuc_driver
    image: ladder99/fanuc-driver:${FOCAS_TGT}
    restart: always
    depends_on:
      - mosquitto
    networks:
      - fanuc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/fanuc-volumes/fanuc-driver:/etc/fanuc:rw
    logging:
      options:
        max-size: "20m"

networks:
  fanuc:
    name: fanuc